import React from 'react';
import { motion } from 'motion/react';
import { FileText, Scale, Gavel, AlertCircle, ChevronLeft, Mail } from 'lucide-react';

const TermsView: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  const sections = [
    {
      title: 'Acceptance of Terms',
      icon: Scale,
      content: 'By accessing or using TutorX AI, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use our services.'
    },
    {
      title: 'User Conduct',
      icon: Gavel,
      content: 'You agree not to use TutorX AI for any unlawful purpose or in any way that could damage, disable, or impair our services. This includes attempting to bypass our AI safety filters.'
    },
    {
      title: 'Intellectual Property',
      icon: FileText,
      content: 'The content generated by our AI is for your personal, educational use. The TutorX AI platform, including its software and branding, is the property of CipherX Inc.'
    },
    {
      title: 'Limitation of Liability',
      icon: AlertCircle,
      content: 'TutorX AI is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service or reliance on AI-generated content.'
    }
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-6 md:p-12 font-sans">
      <div className="max-w-3xl mx-auto space-y-12">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-slate-500 hover:text-white transition-colors text-xs font-black uppercase tracking-widest"
        >
          <ChevronLeft size={16} />
          Back
        </button>

        <header className="space-y-4">
          <div className="w-16 h-16 rounded-2xl bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center">
            <FileText size={32} className="text-indigo-400" />
          </div>
          <h1 className="text-4xl md:text-5xl font-black tracking-tight">Terms of Service</h1>
          <p className="text-slate-500 font-medium text-lg">Last updated: March 17, 2024</p>
        </header>

        <div className="space-y-8">
          {sections.map((section, idx) => (
            <motion.div 
              key={section.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              className="bg-white/5 border border-white/5 rounded-3xl p-8 space-y-4"
            >
              <div className="flex items-center gap-3 text-indigo-400">
                <section.icon size={20} />
                <h2 className="text-xl font-bold tracking-tight">{section.title}</h2>
              </div>
              <p className="text-slate-400 leading-relaxed font-medium">
                {section.content}
              </p>
            </motion.div>
          ))}
        </div>

        <footer className="pt-12 border-t border-white/5 text-center space-y-4">
          <p className="text-slate-500 text-sm font-medium">
            Questions about our terms?
          </p>
          <a 
            href="mailto:cipherxinc@gmail.com"
            className="inline-flex items-center gap-2 text-indigo-400 font-bold hover:text-indigo-300 transition-colors"
          >
            <Mail size={18} />
            cipherxinc@gmail.com
          </a>
        </footer>
      </div>
    </div>
  );
};

export default TermsView;
